"""The structural-scan lane: ast-grep rules derived from the failure registry,
SkillSpector's gate policy, and the scanner pins (TESTING_STANDARDS section 5.1).

Stdlib only, like everything else under tools/wall. The scanners themselves
are dev tooling installed by CI and tools/quality/install.sh; this module never
imports them, it only generates their inputs and judges their outputs.

    quality.py rules [--check]        regenerate (or verify) the derived rules
    quality.py pin <tool>             print a tool's pinned version
    quality.py promoted <tool>        print promoted rule ids, one per line
    quality.py gate-skillspector R..  judge SkillSpector JSON reports
    quality.py bump [--ast-grep V] [--skillspector V]

The derived rules are generated from fenced ```ast-grep blocks in the failure
registry (and the known-issues intake). A registry entry and its rule can never
drift apart: the pre-commit hook regenerates them, and CI and the kit suite run
`rules --check`, which fails on any difference.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

CONFIG = Path("tools") / "quality" / "quality.json"
TOOLS = ("ast-grep", "skillspector")

# An entry heading: `## F-SUBSTR-001 - title` or `### KI-042 - title`. A
# template placeholder (`<F-SCOPE-NNN>`) is not an id and is skipped.
_HEADING = re.compile(r"^(#{1,6})\s+([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+)\b\s*[-:]*\s*(.*)$")
_ANY_HEADING = re.compile(r"^#{1,6}\s")
_FENCE = re.compile(r"^(`{3,}|~{3,})\s*([A-Za-z0-9_-]*)\s*$")
# Keys the generator owns. An author who sets them would silently lose the
# edit on the next regeneration, so a block carrying one is refused.
_OWNED_KEYS = ("id", "severity", "metadata")
GENERATED_HEADER = ("# GENERATED by tools/wall/quality.py from {source} ({cls}).\n"
                    "# Do not edit: change the entry's ```{fence} block and run\n"
                    "#   python3 tools/wall/quality.py rules\n")


class RuleError(ValueError):
    """A registry block that cannot become a rule. Names source and class."""


def load_config(root: Path) -> dict:
    return json.loads((Path(root) / CONFIG).read_text(encoding="utf-8"))


def save_config(root: Path, cfg: dict) -> None:
    (Path(root) / CONFIG).write_text(json.dumps(cfg, indent=2) + "\n",
                                     encoding="utf-8")


# ------------------------------------------------------------ registry parse

def parse_entries(text: str) -> list[dict]:
    """Every id-headed entry with its ```ast-grep and ```ast-grep-test blocks,
    in document order. Blocks outside an id-headed entry are ignored."""
    entries: list[dict] = []
    current = None
    fence = None          # (marker, info, lines, start line) inside a block
    for n, line in enumerate(text.splitlines(), 1):
        if fence is not None:
            if line.strip() == fence[0]:
                _, info, body, _ = fence
                if current is not None and info in ("ast-grep", "ast-grep-test"):
                    key = "rules" if info == "ast-grep" else "tests"
                    current[key].append({"line": fence[3], "body": "\n".join(body)})
                # Any other fence closes silently; its content is prose.
                fence = None
            else:
                fence[2].append(line)
            continue
        m = _FENCE.match(line)
        if m:
            fence = (m.group(1), m.group(2), [], n)
            continue
        h = _HEADING.match(line)
        if h:
            current = {"id": h.group(2), "title": h.group(3).strip(),
                       "rules": [], "tests": [], "line": n}
            entries.append(current)
        elif _ANY_HEADING.match(line):
            current = None
    return entries


def _top_level_keys(body: str) -> set[str]:
    keys = set()
    for line in body.splitlines():
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*)\s*:", line)
        if m:
            keys.add(m.group(1))
    return keys


def rule_id(cls: str, index: int) -> str:
    base = cls.lower()
    return base if index == 0 else "%s-%d" % (base, index + 1)


def render_rules(source: str, text: str) -> dict[str, str]:
    """{filename: content} for rules AND their tests, keyed `rules/<id>.yml`
    and `tests/<id>-test.yml`. Raises RuleError on a malformed entry."""
    out: dict[str, str] = {}
    for e in parse_entries(text):
        if not e["rules"] and not e["tests"]:
            continue
        where = "%s:%d %s" % (source, e["line"], e["id"])
        if len(e["tests"]) != len(e["rules"]):
            raise RuleError(
                "%s: %d ```ast-grep block(s) but %d ```ast-grep-test block(s) -- "
                "every rule needs a test with an `invalid:` case, or nobody can "
                "watch it go red" % (where, len(e["rules"]), len(e["tests"])))
        for i, (rule, test) in enumerate(zip(e["rules"], e["tests"])):
            rid = rule_id(e["id"], i)
            keys = _top_level_keys(rule["body"])
            owned = sorted(keys.intersection(_OWNED_KEYS))
            if owned:
                raise RuleError("%s: the block sets %s, which the generator "
                                "owns -- remove it" % (where, ", ".join(owned)))
            for needed in ("language", "rule"):
                if needed not in keys:
                    raise RuleError("%s: the ```ast-grep block has no `%s:`"
                                    % (where, needed))
            tkeys = _top_level_keys(test["body"])
            if "invalid" not in tkeys:
                raise RuleError("%s: the ```ast-grep-test block has no "
                                "`invalid:` case" % where)
            if "id" in tkeys:
                raise RuleError("%s: the ```ast-grep-test block sets id, which "
                                "the generator owns -- remove it" % where)
            head = GENERATED_HEADER.format(source=source, cls=e["id"],
                                           fence="ast-grep")
            lines = [head.rstrip("\n"),
                     "id: %s" % rid,
                     # Every derived rule starts report-only. Promotion is per
                     # rule, recorded in quality.json, applied at scan time.
                     "severity: warning"]
            if "message" not in keys:
                title = e["title"] or e["id"]
                lines.append("message: %s" % json.dumps("%s - %s" % (e["id"], title)))
            lines += ["metadata:",
                      "  failure_class: %s" % e["id"],
                      "  source: %s" % json.dumps(source),
                      rule["body"].rstrip("\n"), ""]
            out["rules/%s.yml" % rid] = "\n".join(lines)
            thead = GENERATED_HEADER.format(source=source, cls=e["id"],
                                            fence="ast-grep-test")
            out["tests/%s-test.yml" % rid] = "\n".join(
                [thead.rstrip("\n"), "id: %s" % rid,
                 test["body"].rstrip("\n"), ""])
    return out


def expected_tree(root: Path, cfg: dict) -> dict[Path, str]:
    """Every generated file, by absolute path, from every configured source
    that exists. A missing source contributes nothing -- a host that has not
    started its known-issues intake yet is not an error."""
    root = Path(root)
    rules_dir = root / cfg["generated_rules_dir"]
    tests_dir = root / cfg["generated_tests_dir"]
    tree: dict[Path, str] = {}
    seen: dict[str, str] = {}
    for source in cfg.get("failure_sources", []):
        path = root / source
        if not path.is_file():
            continue
        for name, content in render_rules(source, path.read_text(encoding="utf-8")).items():
            kind, fname = name.split("/", 1)
            if kind == "rules":
                if fname in seen:
                    raise RuleError("%s: rule %s is also generated from %s -- "
                                    "one definition per name"
                                    % (source, fname[:-4], seen[fname]))
                seen[fname] = source
            tree[(rules_dir if kind == "rules" else tests_dir) / fname] = content
    return tree


def _generated_on_disk(root: Path, cfg: dict) -> set[Path]:
    found = set()
    for d in (cfg["generated_rules_dir"], cfg["generated_tests_dir"]):
        p = Path(root) / d
        if p.is_dir():
            found.update(f for f in p.glob("*.yml"))
    return found


def check_rules(root: Path, cfg: dict) -> list[str]:
    """Drift between the registry and the generated rules, one line each."""
    want = expected_tree(root, cfg)
    have = _generated_on_disk(root, cfg)
    problems = []
    for path, content in sorted(want.items()):
        rel = path.relative_to(root)
        if not path.is_file():
            problems.append("missing: %s" % rel)
        elif path.read_text(encoding="utf-8") != content:
            problems.append("stale: %s" % rel)
    for path in sorted(have - set(want)):
        problems.append("orphaned (its entry lost its block): %s"
                        % path.relative_to(root))
    return problems


def write_rules(root: Path, cfg: dict) -> list[str]:
    """Regenerate; return what changed. Only the generated dirs are touched."""
    want = expected_tree(root, cfg)
    changed = check_rules(root, cfg)
    for path in _generated_on_disk(root, cfg) - set(want):
        path.unlink()
    for path, content in want.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
    for d in (cfg["generated_rules_dir"], cfg["generated_tests_dir"]):
        # Keep the directory in git even when the registry has no rules yet,
        # so ast-grep's ruleDirs never points at nothing.
        keep = Path(root) / d / ".gitkeep"
        keep.parent.mkdir(parents=True, exist_ok=True)
        if not keep.exists():
            keep.write_text("", encoding="utf-8")
    return changed


# ------------------------------------------------------------ promotions

def promoted(cfg: dict, tool: str) -> list[str]:
    return [p["rule"] for p in cfg.get("promotions", {}).get(tool, [])]


def promotion_problems(cfg: dict) -> list[str]:
    """A promotion without its date and measured standing count is a claim
    nobody can re-check (TESTING_STANDARDS section 5)."""
    problems = []
    for tool in TOOLS:
        for p in cfg.get("promotions", {}).get(tool, []):
            for field in ("rule", "date", "standing_count", "reason"):
                if field not in p:
                    problems.append("%s promotion %r lacks %s"
                                    % (tool, p.get("rule"), field))
            if p.get("standing_count") not in (0, None):
                problems.append("%s promotion %r: a rule is promoted only at "
                                "zero standing findings" % (tool, p.get("rule")))
    return problems


# ------------------------------------------------------------ SkillSpector gate

def judge_skillspector(reports: list[dict], cfg: dict) -> tuple[list[str], list[str]]:
    """(blocking, advisory) finding lines across all reports."""
    policy = cfg["skillspector"]
    block_ids = set(policy.get("always_block", [])) | set(promoted(cfg, "skillspector"))
    blocking, advisory = [], []
    for r in reports:
        src = r.get("skill", {}).get("source", "?")
        if os.path.isabs(src):
            src = os.path.relpath(src)
        risk = r.get("risk_assessment", {})
        if policy.get("block_on_do_not_install") and \
                risk.get("recommendation") == "DO_NOT_INSTALL":
            blocking.append("%s: recommendation DO_NOT_INSTALL (score %s)"
                            % (src, risk.get("score")))
        for i in r.get("issues", []):
            loc = i.get("location", {})
            line = "%s/%s:%s %s %s [%s] %s" % (
                src, loc.get("file", "?"), loc.get("start_line", "?"),
                i.get("id"), i.get("pattern", i.get("category", "")),
                i.get("severity"), (i.get("finding") or "").strip()[:80])
            (blocking if i.get("id") in block_ids else advisory).append(line)
    return blocking, advisory


# ------------------------------------------------------------ pins

def bump(cfg: dict, versions: dict[str, str]) -> list[str]:
    """Move pins to `versions`; the old pin becomes the named rollback.
    Returns one line per tool that moved."""
    moved = []
    for tool, new in versions.items():
        if not new:
            continue
        pin = cfg["tools"][tool]
        if pin["version"] != new:
            moved.append("%s %s -> %s (rollback %s)" % (tool, pin["version"], new,
                                                        pin["version"]))
            pin["rollback"] = pin["version"]
            pin["version"] = new
    return moved


# ------------------------------------------------------------ CLI

def _root() -> Path:
    return Path(__file__).resolve().parent.parent.parent


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="quality.py", description=__doc__.split("\n\n")[0])
    p.add_argument("--root", type=Path, default=None)
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("rules", help="regenerate ast-grep rules from the registry")
    s.add_argument("--check", action="store_true", help="fail on drift, write nothing")
    s = sub.add_parser("pin", help="print a tool's pinned version")
    s.add_argument("tool", choices=TOOLS)
    s = sub.add_parser("promoted", help="print promoted rule ids")
    s.add_argument("tool", choices=TOOLS)
    s = sub.add_parser("gate-skillspector", help="judge SkillSpector JSON reports")
    s.add_argument("reports", nargs="+", type=Path)
    s = sub.add_parser("bump", help="move pins, naming the rollback")
    s.add_argument("--ast-grep", dest="ast_grep", default="")
    s.add_argument("--skillspector", default="")
    a = p.parse_args(argv)
    root = a.root or _root()
    cfg = load_config(root)

    if a.cmd == "rules":
        problems = promotion_problems(cfg)
        try:
            drift = check_rules(root, cfg) if a.check else write_rules(root, cfg)
        except RuleError as exc:
            print("quality: %s" % exc, file=sys.stderr)
            return 1
        if a.check:
            problems += drift
            for line in problems:
                print("quality: %s" % line, file=sys.stderr)
            if drift:
                print("quality: run `python3 tools/wall/quality.py rules` and "
                      "commit the result", file=sys.stderr)
            return 1 if problems else 0
        for line in drift:
            print("quality: regenerated -- %s" % line)
        for line in problems:
            print("quality: %s" % line, file=sys.stderr)
        return 1 if problems else 0
    if a.cmd == "pin":
        print(cfg["tools"][a.tool]["version"])
        return 0
    if a.cmd == "promoted":
        for rid in promoted(cfg, a.tool):
            print(rid)
        return 0
    if a.cmd == "gate-skillspector":
        reports = [json.loads(r.read_text(encoding="utf-8")) for r in a.reports]
        blocking, advisory = judge_skillspector(reports, cfg)
        for line in advisory:
            print("skillspector (report-only): %s" % line)
        for line in blocking:
            print("skillspector BLOCKING: %s" % line)
        print("skillspector: %d blocking, %d report-only across %d report(s)"
              % (len(blocking), len(advisory), len(reports)))
        return 1 if blocking else 0
    if a.cmd == "bump":
        moved = bump(cfg, {"ast-grep": a.ast_grep, "skillspector": a.skillspector})
        if moved:
            save_config(root, cfg)
        for line in moved:
            print(line)
        if not moved:
            print("pins already at the requested versions")
        return 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
