"""The structural-scan lane: ast-grep rules derived from the failure registry,
the gates for SkillSpector and zizmor, the gitleaks suppression record, and
the scanner pins (TESTING_STANDARDS section 5.1).

Stdlib only, like everything else under tools/wall. The scanners themselves
are dev tooling installed by CI and tools/quality/install.sh; this module never
imports them, it only generates their inputs and judges their outputs.

    quality.py rules [--check]        regenerate (or verify) the derived rules
    quality.py suppressions           verify every .gitleaksignore entry is dated
    quality.py proofs                 list custom rules with the fixture proving each
    quality.py baseline-path TARGET   print a SkillSpector target's baseline file
    quality.py history [--ci]         a shallow history: exit 1 in ci, 3 (unknown) locally
    quality.py library-check DIR      render the templates' rule blocks into DIR
                                      (with an sgconfig.yml) for `ast-grep test`
    quality.py pin <tool>             print a tool's pinned version
    quality.py promoted <tool>        print promoted rule ids, one per line
    quality.py install-plan           print what tools/quality/install.sh installs
    quality.py gate-skillspector R..  judge SkillSpector JSON reports
    quality.py gate-zizmor R          judge a zizmor JSON report
    quality.py latest                 resolve every tool's latest release (network)
    quality.py bump --set TOOL=V ...  move pins, naming the rollback

The derived rules are generated from fenced ```ast-grep blocks in the failure
registry (and the known-issues intake). A registry entry and its rule can never
drift apart: the pre-commit hook regenerates them, and CI and the kit suite run
`rules --check`, which fails on any difference.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

CONFIG = Path("tools") / "quality" / "quality.json"
GITLEAKSIGNORE = ".gitleaksignore"
# The growing support files (docs/SCAN_LANE.md). Each custom rule ships with a
# fixture that must trip it, or nobody can watch it go red.
GITLEAKS_CONFIG = ".gitleaks.toml"
GITLEAKS_FIXTURES = Path(".gitleaks") / "fixtures"
YARA_DIR = Path(".skillspector") / "yara"
YARA_FIXTURES = Path(".skillspector") / "fixtures"
BASELINES = Path(".skillspector") / "baselines"
_GITLEAKS_RULE = re.compile(r"^\[\[rules\]\]\s*$(.*?)(?=^\[|\Z)", re.M | re.S)
_GITLEAKS_ID = re.compile(r"^\s*id\s*=\s*['\"]([^'\"]+)['\"]", re.M)
_YARA_RULE = re.compile(r"^\s*(?:(?:private|global)\s+)*rule\s+([A-Za-z_]\w*)", re.M)
_YARA_HIT = re.compile(r"YARA rule '([A-Za-z_]\w*)'")
_DATE = re.compile(r"\b\d{4}-\d{2}-\d{2}\b")

# An entry heading: `## F-SUBSTR-001 - title` or `### KI-042 - title`. A
# template placeholder (`<F-SCOPE-NNN>`) is not an id and is skipped.
_HEADING = re.compile(r"^(#{1,6})\s+([A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+)\b\s*[-:]*\s*(.*)$")
_ANY_HEADING = re.compile(r"^#{1,6}\s")
# CommonMark fences: at most three spaces of indent (four is an indented code
# block, which is how the template shows an example without generating it).
_FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})\s*([^`\s]*)[^`]*$")
_VERSION = re.compile(r"v?\d+(\.\d+)*")
# Keys the generator owns. An author who sets them would silently lose the
# edit on the next regeneration, so a block carrying one is refused.
_OWNED_KEYS = ("id", "severity", "metadata")
GENERATED_HEADER = ("# GENERATED by tools/wall/quality.py from {source} ({cls}).\n"
                    "# Do not edit: change the entry's ```{fence} block and run\n"
                    "#   python3 tools/wall/quality.py rules\n")


class RuleError(ValueError):
    """A registry block that cannot become a rule. Names source and class."""


def load_config(root: Path) -> dict:
    return json.loads((Path(root) / CONFIG).read_text(encoding="utf-8"))


def save_config(root: Path, cfg: dict) -> None:
    (Path(root) / CONFIG).write_text(json.dumps(cfg, indent=2) + "\n",
                                     encoding="utf-8")


# ------------------------------------------------------------ registry parse

def parse_entries(text: str) -> list[dict]:
    """Every id-headed entry with its ```ast-grep and ```ast-grep-test blocks,
    in document order. Blocks outside an id-headed entry are ignored."""
    entries: list[dict] = []
    current = None
    fence = None          # (marker, info, lines, start line) inside a block
    for n, line in enumerate(text.splitlines(), 1):
        if fence is not None:
            # A closer repeats the opener's character at least as many times,
            # with at most three spaces of indent and nothing after it.
            m = re.match(r"^ {0,3}(%s{%d,})\s*$" % (re.escape(fence[0][0]),
                                                  len(fence[0])), line)
            if m:
                _, info, body, _ = fence
                if current is not None and info in ("ast-grep", "ast-grep-test"):
                    key = "rules" if info == "ast-grep" else "tests"
                    current[key].append({"line": fence[3], "body": "\n".join(body)})
                fence = None
            else:
                fence[2].append(line)
            continue
        m = _FENCE.match(line)
        if m:
            fence = (m.group(1), m.group(2), [], n)
            continue
        h = _HEADING.match(line)
        if h:
            current = {"id": h.group(2), "title": h.group(3).strip(),
                       "rules": [], "tests": [], "line": n}
            entries.append(current)
        elif _ANY_HEADING.match(line):
            current = None
    if fence is not None and current is not None and \
            fence[1] in ("ast-grep", "ast-grep-test"):
        # An unclosed rule block would otherwise vanish, and `rules --check`
        # would pass without the guard the author wrote.
        raise RuleError("%d %s: the ```%s block is never closed"
                        % (fence[3], current["id"], fence[1]))
    return entries


def _top_level_keys(body: str) -> set[str]:
    keys = set()
    for line in body.splitlines():
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*)\s*:", line)
        if m:
            keys.add(m.group(1))
    return keys


def rule_id(cls: str, index: int) -> str:
    base = cls.lower()
    return base if index == 0 else "%s-%d" % (base, index + 1)


def render_rules(source: str, text: str) -> dict[str, str]:
    """{filename: content} for rules AND their tests, keyed `rules/<id>.yml`
    and `tests/<id>-test.yml`. Raises RuleError on a malformed entry."""
    out: dict[str, str] = {}
    try:
        entries = parse_entries(text)
    except RuleError as exc:
        raise RuleError("%s:%s" % (source, exc)) from None
    for e in entries:
        if not e["rules"] and not e["tests"]:
            continue
        where = "%s:%d %s" % (source, e["line"], e["id"])
        if len(e["tests"]) != len(e["rules"]):
            raise RuleError(
                "%s: %d ```ast-grep block(s) but %d ```ast-grep-test block(s) -- "
                "every rule needs a test with an `invalid:` case, or nobody can "
                "watch it go red" % (where, len(e["rules"]), len(e["tests"])))
        for i, (rule, test) in enumerate(zip(e["rules"], e["tests"])):
            rid = rule_id(e["id"], i)
            keys = _top_level_keys(rule["body"])
            owned = sorted(keys.intersection(_OWNED_KEYS))
            if owned:
                raise RuleError("%s: the block sets %s, which the generator "
                                "owns -- remove it" % (where, ", ".join(owned)))
            for needed in ("language", "rule"):
                if needed not in keys:
                    raise RuleError("%s: the ```ast-grep block has no `%s:`"
                                    % (where, needed))
            tkeys = _top_level_keys(test["body"])
            if "invalid" not in tkeys:
                raise RuleError("%s: the ```ast-grep-test block has no "
                                "`invalid:` case" % where)
            if "id" in tkeys:
                raise RuleError("%s: the ```ast-grep-test block sets id, which "
                                "the generator owns -- remove it" % where)
            head = GENERATED_HEADER.format(source=source, cls=e["id"],
                                           fence="ast-grep")
            lines = [head.rstrip("\n"),
                     "id: %s" % rid,
                     # Every derived rule starts report-only. Promotion is per
                     # rule, recorded in quality.json, applied at scan time.
                     "severity: warning"]
            if "message" not in keys:
                title = e["title"] or e["id"]
                lines.append("message: %s" % json.dumps("%s - %s" % (e["id"], title)))
            lines += ["metadata:",
                      "  failure_class: %s" % e["id"],
                      "  source: %s" % json.dumps(source),
                      rule["body"].rstrip("\n"), ""]
            out["rules/%s.yml" % rid] = "\n".join(lines)
            thead = GENERATED_HEADER.format(source=source, cls=e["id"],
                                            fence="ast-grep-test")
            out["tests/%s-test.yml" % rid] = "\n".join(
                [thead.rstrip("\n"), "id: %s" % rid,
                 test["body"].rstrip("\n"), ""])
    return out


def expected_tree(root: Path, cfg: dict) -> dict[Path, str]:
    """Every generated file, by absolute path, from every configured source
    that exists. A missing source contributes nothing -- a host that has not
    started its known-issues intake yet is not an error."""
    root = Path(root)
    rules_dir = root / cfg["generated_rules_dir"]
    tests_dir = root / cfg["generated_tests_dir"]
    tree: dict[Path, str] = {}
    seen: dict[str, str] = {}
    for source in cfg.get("failure_sources", []):
        path = root / source
        if not path.is_file():
            continue
        for name, content in render_rules(source, path.read_text(encoding="utf-8")).items():
            kind, fname = name.split("/", 1)
            if kind == "rules":
                if fname in seen:
                    raise RuleError("%s: rule %s is also generated from %s -- "
                                    "one definition per name"
                                    % (source, fname[:-4], seen[fname]))
                seen[fname] = source
            tree[(rules_dir if kind == "rules" else tests_dir) / fname] = content
    return tree


def _generated_on_disk(root: Path, cfg: dict) -> set[Path]:
    found = set()
    for d in (cfg["generated_rules_dir"], cfg["generated_tests_dir"]):
        p = Path(root) / d
        if p.is_dir():
            found.update(f for f in p.glob("*.yml"))
    return found


def check_rules(root: Path, cfg: dict) -> list[str]:
    """Drift between the registry and the generated rules, one line each."""
    want = expected_tree(root, cfg)
    have = _generated_on_disk(root, cfg)
    problems = []
    for path, content in sorted(want.items()):
        rel = path.relative_to(root)
        if not path.is_file():
            problems.append("missing: %s" % rel)
        elif path.read_text(encoding="utf-8") != content:
            problems.append("stale: %s" % rel)
    for path in sorted(have - set(want)):
        problems.append("orphaned (its entry lost its block): %s"
                        % path.relative_to(root))
    return problems


def write_rules(root: Path, cfg: dict) -> list[str]:
    """Regenerate; return what changed. Only the generated dirs are touched."""
    want = expected_tree(root, cfg)
    changed = check_rules(root, cfg)
    for path in _generated_on_disk(root, cfg) - set(want):
        path.unlink()
    for path, content in want.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
    for d in (cfg["generated_rules_dir"], cfg["generated_tests_dir"]):
        # Keep the directory in git even when the registry has no rules yet,
        # so ast-grep's ruleDirs never points at nothing.
        keep = Path(root) / d / ".gitkeep"
        keep.parent.mkdir(parents=True, exist_ok=True)
        if not keep.exists():
            keep.write_text("", encoding="utf-8")
    return changed


# ------------------------------------------------------------ promotions

def promoted(cfg: dict, tool: str) -> list[str]:
    """Promoted rule ids; `*` promotes the whole tool."""
    return [p["rule"] for p in cfg.get("promotions", {}).get(tool, [])]


def promotion_problems(cfg: dict) -> list[str]:
    """A promotion without its date and measured standing count is a claim
    nobody can re-check (TESTING_STANDARDS section 5)."""
    problems = []
    for tool, entries in sorted(cfg.get("promotions", {}).items()):
        if tool not in cfg.get("tools", {}):
            problems.append("promotions name %r, which has no pin" % tool)
        for p in entries:
            for field in ("rule", "date", "standing_count", "reason"):
                if field not in p:
                    problems.append("%s promotion %r lacks %s"
                                    % (tool, p.get("rule"), field))
            count = p.get("standing_count")
            # A measured zero, as an integer: null records no measurement, and
            # False == 0 in Python but is not a count.
            if "standing_count" in p and (type(count) is not int or count != 0):
                problems.append("%s promotion %r: a rule is promoted only at a "
                                "measured zero standing count, not %r"
                                % (tool, p.get("rule"), count))
    return problems


# ------------------------------------------------------------ SkillSpector gate

def judge_skillspector(reports: list[dict], cfg: dict) -> tuple[list[str], list[str]]:
    """(blocking, advisory) finding lines across all reports."""
    policy = cfg["skillspector"]
    block_ids = set(policy.get("always_block", [])) | set(promoted(cfg, "skillspector"))
    # A custom YARA rule reports as a generic YR id; promote it by name with
    # `yara:<rule_name>` so one rule can block without promoting them all.
    blocking, advisory = [], []
    for r in reports:
        src = r.get("skill", {}).get("source", "?")
        if os.path.isabs(src):
            src = os.path.relpath(src)
        risk = r.get("risk_assessment", {})
        if policy.get("block_on_do_not_install") and \
                risk.get("recommendation") == "DO_NOT_INSTALL":
            blocking.append("%s: recommendation DO_NOT_INSTALL (score %s)"
                            % (src, risk.get("score")))
        for i in r.get("issues", []):
            loc = i.get("location", {})
            line = "%s/%s:%s %s %s [%s] %s" % (
                src, loc.get("file", "?"), loc.get("start_line", "?"),
                i.get("id"), i.get("pattern", i.get("category", "")),
                i.get("severity"), (i.get("finding") or "").strip()[:80])
            yara = _YARA_HIT.search(i.get("pattern") or "")
            hit = i.get("id") in block_ids or \
                (yara is not None and "yara:%s" % yara.group(1) in block_ids)
            (blocking if hit else advisory).append(line)
    return blocking, advisory


def baseline_path(target: str) -> Path:
    """`.claude/agents` -> `.skillspector/baselines/claude__agents.yaml`. One
    file per target: SkillSpector refuses a shared baseline across skills."""
    slug = target.strip("/").lstrip("./").replace("/", "__")
    return BASELINES / ("%s.yaml" % slug)


# ------------------------------------------------------------ custom-rule proofs

def gitleaks_rule_ids(toml_text: str) -> list[str]:
    ids = []
    for block in _GITLEAKS_RULE.findall(toml_text):
        m = _GITLEAKS_ID.search(block)
        if m:
            ids.append(m.group(1))
    return ids


def yara_rule_names(text: str) -> list[str]:
    return _YARA_RULE.findall(text)


def proofs(root: Path) -> tuple[list[tuple[str, str, Path]], list[str]]:
    """([(kind, rule, fixture)], problems). Every custom gitleaks rule needs
    `.gitleaks/fixtures/<id>.txt`; every custom YARA rule needs a non-empty
    `.skillspector/fixtures/<rule>/`. A fixture whose rule is gone is named
    too -- it proves nothing and reads as coverage."""
    root = Path(root)
    found, problems = [], []
    cfg = root / GITLEAKS_CONFIG
    ids = gitleaks_rule_ids(cfg.read_text(encoding="utf-8")) if cfg.is_file() else []
    for rid in ids:
        fx = GITLEAKS_FIXTURES / ("%s.txt" % rid)
        if (root / fx).is_file():
            found.append(("gitleaks", rid, fx))
        else:
            problems.append("gitleaks rule %r has no fixture %s" % (rid, fx))
    fxdir = root / GITLEAKS_FIXTURES
    if fxdir.is_dir():
        for f in sorted(fxdir.glob("*.txt")):
            if f.stem not in ids:
                problems.append("fixture %s has no rule in %s"
                                % (f.relative_to(root), GITLEAKS_CONFIG))
    names = []
    ydir = root / YARA_DIR
    if ydir.is_dir():
        for f in sorted(ydir.glob("*.yar")) + sorted(ydir.glob("*.yara")):
            names += yara_rule_names(f.read_text(encoding="utf-8"))
    for name in names:
        fx = YARA_FIXTURES / name
        if (root / fx).is_dir() and any((root / fx).iterdir()):
            found.append(("yara", name, fx))
        else:
            problems.append("YARA rule %r has no fixture directory %s/" % (name, fx))
    yfx = root / YARA_FIXTURES
    if yfx.is_dir():
        for d in sorted(p for p in yfx.iterdir() if p.is_dir()):
            if d.name not in names:
                problems.append("fixture %s/ has no YARA rule" % d.relative_to(root))
    return found, problems


# ------------------------------------------------------------ zizmor gate

def judge_zizmor(findings: list[dict], cfg: dict) -> tuple[list[str], list[str]]:
    """(blocking, advisory) lines. A finding zizmor itself marks ignored (an
    inline `# zizmor: ignore[...]`, which carries its reason) is neither."""
    ids = set(promoted(cfg, "zizmor"))
    blocking, advisory = [], []
    for f in findings:
        if f.get("ignored"):
            continue
        where = "?"
        for loc in f.get("locations", []):
            sym = loc.get("symbolic", {})
            if sym.get("kind") == "Primary":
                path = sym.get("key", {}).get("Local", {}).get("verbatim_path", "?")
                row = loc.get("concrete", {}).get("location", {}) \
                         .get("start_point", {}).get("row")
                where = "%s:%s" % (path, "?" if row is None else row + 1)
                break
        sev = f.get("determinations", {}).get("severity", "?")
        line = "%s %s [%s] %s" % (where, f.get("ident"), sev, f.get("desc", ""))
        (blocking if "*" in ids or f.get("ident") in ids else advisory).append(line)
    return blocking, advisory


# ------------------------------------------------------------ gitleaks record

def suppression_problems(text: str) -> list[str]:
    """Every .gitleaksignore fingerprint sits under a comment naming the reason
    and the date. A secrets finding is never report-only; a suppression is a
    claim that the match is not a secret, and a reviewer must be able to
    re-check it (TESTING_STANDARDS section 5)."""
    problems, comment = [], None
    for n, line in enumerate(text.splitlines(), 1):
        s = line.strip()
        if not s:
            comment = None
        elif s.startswith("#"):
            comment = s if comment is None else comment + " " + s
        elif comment is None or not _DATE.search(comment) or \
                len(_DATE.sub("", comment).strip("# -:")) < 12:
            problems.append("%s:%d suppresses %s without a dated reason in the "
                            "comment above it" % (GITLEAKSIGNORE, n, s))
    return problems


# ------------------------------------------------------------ the library

def library_tree(root: Path, cfg: dict, out: Path) -> dict[Path, str]:
    """The rule blocks in the shipped templates, rendered under `out`.

    Adopting repositories get these as live rules the moment `bootstrap`
    copies a template into place, so the kit proves them here first. They are
    rendered apart from the kit's own generated rules on purpose: a class the
    kit has promoted appears in both its registry and its library, under one
    id, and the two must not collide."""
    root, out = Path(root), Path(out)
    tree: dict[Path, str] = {}
    for source in cfg.get("library_sources", []):
        path = root / source
        if not path.is_file():
            raise RuleError("%s: library source is missing" % source)
        for name, content in render_rules(source, path.read_text(encoding="utf-8")).items():
            kind, fname = name.split("/", 1)
            target = out / ("rules" if kind == "rules" else "rule-tests") / fname
            if target in tree:
                raise RuleError("%s: rule %s is also in another library source"
                                % (source, fname))
            tree[target] = content
    tree[out / "sgconfig.yml"] = ("ruleDirs:\n  - rules\n"
                                  "testConfigs:\n  - testDir: rule-tests\n")
    return tree


# ------------------------------------------------------------ full view

def history_problem(root: Path) -> str | None:
    """None when the git history is complete; otherwise why it is not.

    F-PARTIAL-VIEW-001: a history scan over a shallow clone passes on the
    commits it can see, and the commits it cannot see are exactly the ones a
    full-history gate will fail on (measured: a fixture's first commit, hidden
    by a 50-commit clone, turned CI red after the local scan said clean)."""
    try:
        # S603/S607: a fixed argv (no shell), git resolved from PATH.
        out = subprocess.run(  # noqa: S603
            ["git", "-C", str(root), "rev-parse", "--is-shallow-repository"],  # noqa: S607
            capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "not a git work tree -- the history cannot be scanned at all"
    if out == "true":
        return ("shallow clone -- a history scan sees only the fetched commits "
                "(fix: git fetch --unshallow; CI: checkout fetch-depth: 0)")
    return None


# ------------------------------------------------------------ pins

def install_plan(cfg: dict) -> list[str]:
    """`pip <spec>` or `release <owner/repo> <version>` per tool, in config
    order. The shell installer is a loop over these lines and nothing else."""
    plan = []
    for name, pin in cfg["tools"].items():
        scheme, _, where = pin["install"].partition(":")
        v = pin["version"]
        if scheme == "pypi":
            plan.append("pip %s==%s" % (where, v))
        elif scheme == "git":
            plan.append("pip %s @ git+%s.git@%s" % (name, where, v))
        elif scheme == "github-release":
            plan.append("release %s %s" % (where, v))
        else:
            raise ValueError("%s: unknown install scheme %r" % (name, scheme))
    return plan


def version_key(v: str) -> tuple:
    """Numeric ordering for release tags: v2.10.0 sorts after v2.9.6."""
    return tuple(int(x) for x in re.findall(r"\d+", v))


def _tags(url: str) -> list[str]:
    # S603/S607: a fixed argv (no shell), git resolved from PATH like every
    # other git call in the kit; `url` comes from the pinned quality.json.
    out = subprocess.run(["git", "ls-remote", "--tags", "--refs", url],  # noqa: S603, S607
                         capture_output=True, text=True, check=True).stdout
    return [line.split("refs/tags/", 1)[1] for line in out.splitlines()
            if "refs/tags/" in line]


def _stable(tags: list[str]) -> list[str]:
    return [t for t in tags if re.fullmatch(r"v?\d+(\.\d+)*", t)]


def latest(cfg: dict) -> dict[str, str]:
    """Each tool's newest stable release, in the pin's own spelling."""
    found = {}
    for name, pin in cfg["tools"].items():
        scheme, _, where = pin["install"].partition(":")
        if scheme == "pypi":
            # S310: a literal https:// URL, so no file: or custom scheme.
            with urllib.request.urlopen("https://pypi.org/pypi/%s/json" % where,  # noqa: S310
                                        timeout=30) as r:
                found[name] = json.load(r)["info"]["version"]
        elif scheme == "git":
            found[name] = max(_stable(_tags(where)), key=version_key)
        elif scheme == "github-release":
            tag = max(_stable(_tags("https://github.com/%s" % where)), key=version_key)
            found[name] = tag.lstrip("v")
    return found


def bump(cfg: dict, versions: dict[str, str]) -> list[str]:
    """Move pins to `versions`; the old pin becomes the named rollback.
    Returns one line per tool that moved."""
    moved = []
    for tool, new in versions.items():
        if not new:
            continue
        if not _VERSION.fullmatch(new):
            # Release names come from PyPI and git tags; anything that is not
            # a plain version never reaches the config (or a shell).
            raise ValueError("%s: %r is not a release version" % (tool, new))
        pin = cfg["tools"][tool]
        if pin["version"] != new:
            moved.append("%s %s -> %s (rollback %s)" % (tool, pin["version"], new,
                                                        pin["version"]))
            pin["rollback"] = pin["version"]
            pin["version"] = new
    return moved


# ------------------------------------------------------------ CLI

def _root() -> Path:
    return Path(__file__).resolve().parent.parent.parent


def main(argv=None) -> int:
    p = argparse.ArgumentParser(prog="quality.py", description=__doc__.split("\n\n")[0])
    p.add_argument("--root", type=Path, default=None)
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("rules", help="regenerate ast-grep rules from the registry")
    s.add_argument("--check", action="store_true", help="fail on drift, write nothing")
    sub.add_parser("suppressions", help="verify .gitleaksignore entries are dated")
    sub.add_parser("proofs", help="list custom rules and the fixture proving each")
    s = sub.add_parser("baseline-path", help="a SkillSpector target's baseline file")
    s.add_argument("target")
    s = sub.add_parser("library-check", help="render the templates' rules for ast-grep test")
    s.add_argument("out", type=Path)
    s = sub.add_parser("history", help="refuse (--ci) or warn on a shallow history")
    s.add_argument("--ci", action="store_true",
                   help="a partial history is UNKNOWN, not clean: exit 1")
    s = sub.add_parser("pin", help="print a tool's pinned version")
    s.add_argument("tool")
    s = sub.add_parser("promoted", help="print promoted rule ids")
    s.add_argument("tool")
    sub.add_parser("install-plan", help="print what install.sh installs")
    s = sub.add_parser("gate-skillspector", help="judge SkillSpector JSON reports")
    s.add_argument("reports", nargs="+", type=Path)
    s = sub.add_parser("gate-zizmor", help="judge a zizmor JSON report")
    s.add_argument("report", type=Path)
    sub.add_parser("latest", help="print TOOL=VERSION for every latest release")
    s = sub.add_parser("bump", help="move pins, naming the rollback")
    s.add_argument("--set", dest="sets", action="append", default=[],
                   metavar="TOOL=VERSION")
    a = p.parse_args(argv)
    root = a.root or _root()
    cfg = load_config(root)
    for tool in (getattr(a, "tool", None),) + tuple(
            s.partition("=")[0] for s in getattr(a, "sets", [])):
        if tool is not None and tool not in cfg["tools"]:
            p.error("unknown tool %r (pinned: %s)" % (tool, ", ".join(cfg["tools"])))

    if a.cmd == "rules":
        problems = promotion_problems(cfg)
        try:
            drift = check_rules(root, cfg) if a.check else write_rules(root, cfg)
        except RuleError as exc:
            print("quality: %s" % exc, file=sys.stderr)
            return 1
        if a.check:
            problems += drift
            for line in problems:
                print("quality: %s" % line, file=sys.stderr)
            if drift:
                print("quality: run `python3 tools/wall/quality.py rules` and "
                      "commit the result", file=sys.stderr)
            return 1 if problems else 0
        for line in drift:
            print("quality: regenerated -- %s" % line)
        for line in problems:
            print("quality: %s" % line, file=sys.stderr)
        return 1 if problems else 0
    if a.cmd == "suppressions":
        path = Path(root) / GITLEAKSIGNORE
        problems = suppression_problems(path.read_text(encoding="utf-8")) \
            if path.is_file() else []
        for line in problems:
            print("quality: %s" % line, file=sys.stderr)
        return 1 if problems else 0
    if a.cmd == "proofs":
        found, problems = proofs(root)
        for kind, rule, fx in found:
            print("%s %s %s" % (kind, rule, fx))
        for line in problems:
            print("quality: %s" % line, file=sys.stderr)
        return 1 if problems else 0
    if a.cmd == "library-check":
        try:
            tree = library_tree(root, cfg, a.out)
        except RuleError as exc:
            print("quality: %s" % exc, file=sys.stderr)
            return 1
        for path, content in tree.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        (a.out / "rules").mkdir(parents=True, exist_ok=True)
        (a.out / "rule-tests").mkdir(parents=True, exist_ok=True)
        print("library: %d rule(s) rendered" % (len(tree) // 2))
        return 0
    if a.cmd == "history":
        why = history_problem(root)
        if why is None:
            return 0
        if a.ci:
            print("scan: %s -- UNKNOWN, not clean (F-PARTIAL-VIEW-001)" % why,
                  file=sys.stderr)
            return 1
        print("scan: %s -- the local result covers less than CI will" % why,
              file=sys.stderr)
        # Distinct from a finding (1): the caller records UNKNOWN and goes on.
        return 3
    if a.cmd == "baseline-path":
        print(baseline_path(a.target))
        return 0
    if a.cmd == "install-plan":
        for line in install_plan(cfg):
            print(line)
        return 0
    if a.cmd == "latest":
        for name, v in latest(cfg).items():
            print("%s=%s" % (name, v))
        return 0
    if a.cmd == "gate-zizmor":
        try:
            findings = json.loads(a.report.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            print("zizmor: unreadable report (%s) -- not clean, unknown" % exc,
                  file=sys.stderr)
            return 1
        blocking, advisory = judge_zizmor(findings, cfg)
        for line in advisory:
            print("zizmor (report-only): %s" % line)
        for line in blocking:
            print("zizmor BLOCKING: %s" % line)
        print("zizmor: %d blocking, %d report-only" % (len(blocking), len(advisory)))
        return 1 if blocking else 0
    if a.cmd == "pin":
        print(cfg["tools"][a.tool]["version"])
        return 0
    if a.cmd == "promoted":
        for rid in promoted(cfg, a.tool):
            print(rid)
        return 0
    if a.cmd == "gate-skillspector":
        reports = [json.loads(r.read_text(encoding="utf-8")) for r in a.reports]
        blocking, advisory = judge_skillspector(reports, cfg)
        for line in advisory:
            print("skillspector (report-only): %s" % line)
        for line in blocking:
            print("skillspector BLOCKING: %s" % line)
        print("skillspector: %d blocking, %d report-only across %d report(s)"
              % (len(blocking), len(advisory), len(reports)))
        return 1 if blocking else 0
    if a.cmd == "bump":
        try:
            moved = bump(cfg, dict(s.partition("=")[::2] for s in a.sets))
        except ValueError as exc:
            print("quality: %s" % exc, file=sys.stderr)
            return 1
        if moved:
            save_config(root, cfg)
        for line in moved:
            print(line)
        if not moved:
            print("pins already at the requested versions")
        return 0
    return 2


if __name__ == "__main__":
    sys.exit(main())
