#!/usr/bin/env python3
"""testkit.py -- measure test durations, balance test shards, detect drift.

See docs/TESTING_STANDARDS.md section 6. The short version:

* A splitter with no measured durations falls back to splitting by test COUNT,
  and the slow tests clump. Measured: one shard ran about 20 minutes while its
  siblings finished in 4 to 14.
* So shards are packed by MEASURED duration, longest test first, into the
  lightest shard, with ties broken by a stable field -- the same input must
  produce the same map on a re-run.
* The map is DERIVED state. It is regenerated by this tool and never hand
  edited, and it is committed through the normal PR path like any other
  generated file.

Terminology: a "test shard" here is a parallel slice of the test suite. It has
nothing to do with the ledger's EVENT shards (`.wall/events/<day>/<sid>.jsonl`);
the two never share a file, a directory or a command.

Two hazards the API is shaped against:

* `parse_durations` takes a `Path` as a path and a `str` as TEXT, always.
  Sniffing which one a string is would make the result depend on what happens
  to exist on disk.
* `select` returns the node ids for one shard. An EMPTY list is a legitimate
  answer for an empty shard, and passing it to `pytest` as arguments runs the
  WHOLE suite. A caller must check for empty before building a command line.

Stdlib only. No network. No model calls.

    python3 -m testkit durations --input durations.txt
    python3 -m testkit balance --shards 4 --input durations.txt --write
    python3 -m testkit check --repo . --input durations.txt
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path
from typing import Any, NamedTuple

SCHEMA_VERSION = 1

#: Where the map lives, relative to the repo root. Derived state, so it sits
#: beside the other generated config rather than in the source tree.
SHARD_MAP_RELPATH = Path(".wall") / "config" / "shards.json"

#: `slowest N durations` lines: "0.12s call     tests/test_x.py::test_y".
#: The three phases of one test are SUMMED -- balancing is about wall time, and
#: setup is wall time.
_DURATION_LINE = re.compile(
    r"^\s*(?P<secs>\d+(?:\.\d+)?)s\s+(?P<phase>call|setup|teardown)\s+(?P<test>\S.*?)\s*$"
)

#: Default rebalance trigger: slowest shard over 1.5x the median shard.
DEFAULT_IMBALANCE_THRESHOLD = 1.5


class TestkitError(Exception):
    """Base for every error this module raises, so a caller can catch one name."""


class DurationsError(TestkitError):
    """The durations input could not be read as durations."""


class BalanceError(TestkitError):
    """The balance request or its stats were not usable."""


class ShardMapError(TestkitError):
    """The shard map is missing, malformed, or indexed out of range."""


class BalanceResult(NamedTuple):
    shards: list[list[str]]
    stats: dict[str, Any]


# --------------------------------------------------------------- durations

def _coerce_seconds(test_id: Any, value: Any) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise DurationsError(
            "duration for %r is %s, expected a number" % (test_id, type(value).__name__))
    secs = float(value)
    if math.isnan(secs) or math.isinf(secs):
        raise DurationsError("duration for %r is not finite" % (test_id,))
    if secs < 0:
        raise DurationsError("duration for %r is negative (%r)" % (test_id, secs))
    return secs


def _parse_json_durations(text: str, origin: str) -> dict[str, float]:
    try:
        doc = json.loads(text)
    except json.JSONDecodeError as exc:
        raise DurationsError("%s: malformed JSON at line %d column %d: %s"
                             % (origin, exc.lineno, exc.colno, exc.msg)) from exc
    if not isinstance(doc, dict):
        raise DurationsError(
            "%s: durations JSON must be an object mapping test id to seconds, got %s"
            % (origin, type(doc).__name__))
    out: dict[str, float] = {}
    for test_id, value in doc.items():
        if not isinstance(test_id, str) or not test_id.strip():
            raise DurationsError("%s: empty or non-string test id %r" % (origin, test_id))
        out[test_id] = _coerce_seconds(test_id, value)
    return out


def parse_durations(source: str | Path, *, problems: list[str] | None = None
                    ) -> dict[str, float]:
    """Read per-test durations from pytest text or from a JSON object.

    `source` is a `Path` (read from disk) or a `str` (the text itself). The two
    are never sniffed apart: a string is text, always.

    Accepts either `pytest --durations=0 -q` output -- where the setup, call and
    teardown lines of one test are summed -- or a `{"test_id": seconds}` JSON
    object. A `.json` path is parsed as JSON and fails loudly if it is not.

    Unrecognised text lines are skipped. A skipped line that LOOKS like a record
    (it contains a `::` node id) is appended to `problems` when one is supplied,
    so a caller can report "I dropped 40 records" instead of a quiet short read.

    Empty input is an empty mapping, not an error. A missing file is an error.
    """
    if isinstance(source, Path):
        origin = str(source)
        try:
            text = source.read_text(encoding="utf-8")
        except FileNotFoundError as exc:
            raise DurationsError("no durations file at %s" % origin) from exc
        except OSError as exc:
            raise DurationsError("cannot read %s: %s" % (origin, exc)) from exc
        if source.suffix == ".json":
            return _parse_json_durations(text, origin)
    elif isinstance(source, str):
        origin, text = "<text>", source
    else:
        raise DurationsError(
            "source must be a str (text) or a Path, got %s" % type(source).__name__)

    if not text.strip():
        return {}
    # Both JSON openers, not just `{`: a JSON ARRAY fed to the line parser
    # matches nothing and returns an empty mapping, which reads as "the suite
    # has no tests" instead of "this is the wrong shape". Membership over a
    # tuple, not over the string "{[", because `"" in "{["` is True.
    if text.lstrip()[:1] in ("{", "["):
        return _parse_json_durations(text, origin)

    out: dict[str, float] = {}
    for lineno, line in enumerate(text.splitlines(), 1):
        match = _DURATION_LINE.match(line)
        if match is None:
            if "::" in line and problems is not None:
                problems.append("%s:%d: unparsed duration line: %s"
                                % (origin, lineno, line.strip()[:120]))
            continue
        test_id = match.group("test")
        out[test_id] = out.get(test_id, 0.0) + float(match.group("secs"))
    return out


# ----------------------------------------------------------------- balance

def _median(values: list[float]) -> float:
    ordered = sorted(values)
    n = len(ordered)
    if n == 0:
        raise BalanceError("median of no shards")
    mid = n // 2
    if n % 2:
        return ordered[mid]
    return (ordered[mid - 1] + ordered[mid]) / 2.0


def _imbalance(totals: list[float]) -> float:
    """Slowest shard over the median shard.

    An all-zero split is balanced (1.0). A non-zero maximum over a zero median
    is maximally imbalanced and says so with `inf` rather than dividing by zero
    or quietly reporting 1.0 -- half the shards being empty is the case a
    rebalance most needs to see.
    """
    high = max(totals)
    mid = _median(totals)
    if mid == 0.0:
        return 1.0 if high == 0.0 else math.inf
    return high / mid


def balance(durations: dict[str, float], n_shards: int) -> BalanceResult:
    """Greedy longest-first bin-packing of tests into `n_shards` shards.

    Deterministic: tests are ordered by descending duration with the test id as
    the tie-break, so a tie cannot make the map depend on dict order. (A bare
    sort over tuples reaches the second element only on a tie, which is exactly
    the case no hand-written fixture constructs.)

    Returns the shards and a stats dict carrying `totals`, `counts`, `median`,
    `max`, `min`, `total`, `n_shards`, `n_tests` and `imbalance`.
    """
    if isinstance(n_shards, bool) or not isinstance(n_shards, int):
        raise BalanceError("n_shards must be an int, got %s" % type(n_shards).__name__)
    if n_shards < 1:
        raise BalanceError("n_shards must be >= 1, got %d" % n_shards)
    if not isinstance(durations, dict):
        raise BalanceError("durations must be a mapping, got %s"
                           % type(durations).__name__)

    clean = {tid: _coerce_seconds(tid, secs) for tid, secs in durations.items()}
    order = sorted(clean.items(), key=lambda kv: (-kv[1], kv[0]))

    shards: list[list[str]] = [[] for _ in range(n_shards)]
    totals = [0.0] * n_shards
    for test_id, secs in order:
        target = totals.index(min(totals))
        shards[target].append(test_id)
        totals[target] += secs

    stats = {
        "n_shards": n_shards,
        "n_tests": len(clean),
        "totals": [round(t, 6) for t in totals],
        "counts": [len(s) for s in shards],
        "total": round(sum(totals), 6),
        "max": round(max(totals), 6),
        "min": round(min(totals), 6),
        "median": round(_median(totals), 6),
        "imbalance": _imbalance(totals),
    }
    return BalanceResult(shards=shards, stats=stats)


def needs_rebalance(stats: dict[str, Any],
                    threshold: float = DEFAULT_IMBALANCE_THRESHOLD) -> bool:
    """True when the slowest shard exceeds `threshold` x the median shard.

    Strictly greater: a ratio of exactly the threshold is balanced.
    """
    if not isinstance(stats, dict):
        raise BalanceError("stats must be a mapping, got %s" % type(stats).__name__)
    if "imbalance" not in stats:
        raise BalanceError("stats has no 'imbalance' key; pass the stats from balance()")
    value = stats["imbalance"]
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise BalanceError("imbalance must be a number, got %s" % type(value).__name__)
    return float(value) > float(threshold)


# --------------------------------------------------------------- shard map

def shard_map_path(repo: str | Path) -> Path:
    return Path(repo) / SHARD_MAP_RELPATH


def _json_safe(value: Any) -> Any:
    """Replace non-finite floats with None.

    `inf` is a real answer from `_imbalance` and is not JSON. Writing it as
    `Infinity` produces a file most parsers reject, so it is stored as null --
    absent, which is honest -- rather than clamped to a number that reads as a
    measurement.
    """
    if isinstance(value, dict):
        return {k: _json_safe(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_json_safe(v) for v in value]
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def _validate_shards(obj: Any) -> list[list[str]]:
    """Lists and tuples only, checked before anything is iterated.

    Deliberately not "any iterable, coerced with `list()`": `list("abc")` is
    `["a", "b", "c"]` and `list({"a": 1})` is `["a"]`, so a coercing validator
    accepts a string or a dict as a shard structure and reports nothing. An
    explicit `str`/`bytes` rejection is NOT written here on top of the type
    check -- it would be unreachable, and a guard no mutation can kill is dead
    scaffolding that reads as coverage.
    """
    if not isinstance(obj, (list, tuple)):
        raise ShardMapError("shards must be a list of lists, got %s"
                            % type(obj).__name__)
    out: list[list[str]] = []
    for i, shard in enumerate(obj):
        if not isinstance(shard, (list, tuple)):
            raise ShardMapError("shard %d must be a list, got %s"
                                % (i + 1, type(shard).__name__))
        for test_id in shard:
            if not isinstance(test_id, str) or not test_id.strip():
                raise ShardMapError("shard %d holds a non-string test id %r"
                                    % (i + 1, test_id))
        out.append(list(shard))
    return out


def _shards_of(shard_map: Any) -> list[list[str]]:
    """Accept either the written document or a bare list of shards."""
    if isinstance(shard_map, dict):
        if "shards" not in shard_map:
            raise ShardMapError("shard map document has no 'shards' key")
        return _validate_shards(shard_map["shards"])
    return _validate_shards(shard_map)


def write_shard_map(repo: str | Path, shards: list[list[str]],
                    stats: dict[str, Any] | None = None) -> Path:
    """Write `.wall/config/shards.json`. Derived state -- never hand-edited.

    `shards` is a list (or tuple) of lists of node ids -- what `balance`
    returns. Other iterables are refused by name rather than coerced.
    """
    listed = _validate_shards(shards)
    path = shard_map_path(repo)
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "schema_version": SCHEMA_VERSION,
        "generator": "tools/wall/testkit.py",
        "note": "Derived from measured durations. Regenerate, never hand-edit.",
        "shards": listed,
        "stats": _json_safe(stats) if stats is not None else None,
    }
    path.write_text(json.dumps(doc, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    return path


def load_shard_map(repo: str | Path) -> list[list[str]]:
    """Read the shard map. Raises rather than returning an empty map: an empty
    map and an absent one select the same tests (none), and only one of them is
    a configuration."""
    path = shard_map_path(repo)
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise ShardMapError(
            "no shard map at %s; run `testkit balance --shards N --write`" % path) from exc
    except OSError as exc:
        raise ShardMapError("cannot read %s: %s" % (path, exc)) from exc
    try:
        doc = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ShardMapError("malformed shard map %s at line %d column %d: %s"
                            % (path, exc.lineno, exc.colno, exc.msg)) from exc
    return _shards_of(doc)


def select(shard_map: Any, index: int) -> list[str]:
    """Node ids for one shard, ready to append to a pytest command line.

    `index` is **1-based**, matching the convention of the splitters this
    replaces. An empty shard returns an empty list, which is a correct answer
    and a trap: `pytest` with no arguments runs everything. Check for empty
    before building the command.
    """
    shards = _shards_of(shard_map)
    if isinstance(index, bool) or not isinstance(index, int):
        raise ShardMapError("shard index must be an int, got %s" % type(index).__name__)
    if index < 1 or index > len(shards):
        raise ShardMapError("shard index %d out of range; valid range is 1..%d (1-based)"
                            % (index, len(shards)))
    return list(shards[index - 1])


def shard_drift(shard_map: Any, durations: dict[str, float]) -> dict[str, list[str]]:
    """Test ids the map names that the durations do not, and the reverse.

    A map whose ids no longer exist runs fewer tests than it names, which is a
    gate that stopped gating without failing.
    """
    mapped = {tid for shard in _shards_of(shard_map) for tid in shard}
    measured = set(durations)
    return {
        "mapped_not_measured": sorted(mapped - measured),
        "measured_not_mapped": sorted(measured - mapped),
    }


# --------------------------------------------------------------------- CLI

def _read_input(arg: str | None) -> tuple[str | Path, str]:
    if arg in (None, "-"):
        return sys.stdin.read(), "<stdin>"
    return Path(arg), arg


def _load(arg: str | None) -> tuple[dict[str, float], list[str]]:
    source, _origin = _read_input(arg)
    problems: list[str] = []
    return parse_durations(source, problems=problems), problems


def _cmd_durations(args: argparse.Namespace) -> int:
    durations, problems = _load(args.input)
    if args.json:
        print(json.dumps(durations, indent=2, sort_keys=True))
    else:
        total = sum(durations.values())
        print("tests measured : %d" % len(durations))
        print("total seconds  : %.3f" % total)
        for test_id, secs in sorted(durations.items(), key=lambda kv: (-kv[1], kv[0]))[:10]:
            print("  %8.3fs  %s" % (secs, test_id))
    for problem in problems:
        print("problem: %s" % problem, file=sys.stderr)
    return 0


def _cmd_balance(args: argparse.Namespace) -> int:
    durations, problems = _load(args.input)
    result = balance(durations, args.shards)
    for i, (shard, total) in enumerate(zip(result.shards, result.stats["totals"]), 1):
        print("shard %d: %4d tests  %9.3fs" % (i, len(shard), total))
    print("imbalance: %s (threshold %.2f)"
          % (_fmt_ratio(result.stats["imbalance"]), args.threshold))
    if args.write:
        path = write_shard_map(args.repo, result.shards, result.stats)
        print("wrote %s" % path)
    for problem in problems:
        print("problem: %s" % problem, file=sys.stderr)
    return 1 if needs_rebalance(result.stats, args.threshold) else 0


def _cmd_check(args: argparse.Namespace) -> int:
    shards = load_shard_map(args.repo)
    if args.input is None:
        print("check needs measured durations: pass --input (or - for stdin)",
              file=sys.stderr)
        return 2
    durations, problems = _load(args.input)
    totals = [round(sum(durations.get(t, 0.0) for t in shard), 6) for shard in shards]
    stats = {
        "n_shards": len(shards),
        "n_tests": sum(len(s) for s in shards),
        "totals": totals,
        "counts": [len(s) for s in shards],
        "total": round(sum(totals), 6),
        "max": round(max(totals), 6) if totals else 0.0,
        "min": round(min(totals), 6) if totals else 0.0,
        "median": round(_median(totals), 6) if totals else 0.0,
        "imbalance": _imbalance(totals) if totals else 1.0,
    }
    for i, (shard, total) in enumerate(zip(shards, totals), 1):
        print("shard %d: %4d tests  %9.3fs" % (i, len(shard), total))
    print("imbalance: %s (threshold %.2f)"
          % (_fmt_ratio(stats["imbalance"]), args.threshold))

    drift = shard_drift(shards, durations)
    for key in ("mapped_not_measured", "measured_not_mapped"):
        if drift[key]:
            print("drift %s: %d (e.g. %s)" % (key, len(drift[key]), drift[key][0]))
    for problem in problems:
        print("problem: %s" % problem, file=sys.stderr)

    if needs_rebalance(stats, args.threshold):
        print("REBALANCE: slowest shard exceeds %.2fx the median" % args.threshold)
        return 1
    if any(drift[k] for k in drift):
        print("REBALANCE: the map and the measurements no longer describe the same suite")
        return 1
    print("balanced")
    return 0


def _fmt_ratio(value: float) -> str:
    return "inf" if not math.isfinite(float(value)) else "%.2f" % float(value)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="testkit", description=__doc__.splitlines()[0])
    sub = p.add_subparsers(dest="cmd", required=True)

    d = sub.add_parser("durations", help="parse measured durations and summarise")
    d.add_argument("--input", help="path to pytest output or a JSON object; - for stdin")
    d.add_argument("--json", action="store_true", help="emit the parsed mapping")
    d.set_defaults(fn=_cmd_durations)

    b = sub.add_parser("balance", help="pack tests into shards by measured duration")
    b.add_argument("--shards", type=int, required=True)
    b.add_argument("--input", help="path to pytest output or a JSON object; - for stdin")
    b.add_argument("--repo", default=".", help="repo root for --write")
    b.add_argument("--write", action="store_true", help="write .wall/config/shards.json")
    b.add_argument("--threshold", type=float, default=DEFAULT_IMBALANCE_THRESHOLD)
    b.set_defaults(fn=_cmd_balance)

    c = sub.add_parser("check", help="re-score the committed map against fresh durations")
    c.add_argument("--repo", default=".")
    c.add_argument("--input", help="path to pytest output or a JSON object; - for stdin")
    c.add_argument("--threshold", type=float, default=DEFAULT_IMBALANCE_THRESHOLD)
    c.set_defaults(fn=_cmd_check)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.fn(args)
    except TestkitError as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
